import { Course, Module } from '@/types';
import api from './axiosInstance';

export const courseApi = {
  getAll:      (params?: { search?: string; status?: string })  => api.get('/api/v1/courses', { params }),
  checkCode:   (code: string)  => api.get('/api/v1/courses/check-code', { params: { code } }),
  getOne:      (id: string)    => api.get(`/api/v1/courses/${id}`),
  create:      (data: Partial<Course>)     => api.post('/api/v1/courses', data),
  update:      (id: string, data: Partial<Course>)   => api.put(`/api/v1/courses/${id}`, data),
  delete:      (id: string)    => api.delete(`/api/v1/courses/${id}`),
  getStudents: (id: string)    => api.get(`/api/v1/courses/${id}/students`),
  enrollStudents: (id: string, studentIds: string[]) => api.post(`/api/v1/courses/${id}/students`, { studentIds }),
  enroll:      (id: string)    => api.post(`/api/v1/courses/${id}/enroll`),
  drop:        (id: string)    => api.delete(`/api/v1/courses/${id}/enroll`),
  getMyCourses: ()             => api.get('/api/v1/students/me/courses'),
  getModules:  (id: string)    => api.get(`/api/v1/courses/${id}/modules`),
  createModule:(id: string, data: Partial<Module>)   => api.post(`/api/v1/courses/${id}/modules`, data),
  createLesson:(id: string, modId: string, formData: FormData) => api.post(`/api/v1/courses/${id}/modules/${modId}/lessons`, formData, {
    headers: { 'Content-Type': 'multipart/form-data' },
  }),
  getAssignments: (id: string) => api.get(`/api/v1/courses/${id}/assignments`),
  createAssignment:(id: string, data: Record<string, unknown>)=> api.post(`/api/v1/courses/${id}/assignments`, data),
  getQuizzes:  (id: string)    => api.get(`/api/v1/courses/${id}/quizzes`),
  createQuiz:  (id: string, data: Record<string, unknown>)   => api.post(`/api/v1/courses/${id}/quizzes`, data),
  getGradebook:(id: string)    => api.get(`/api/v1/courses/${id}/gradebook`),
  getAnalytics:(id: string)    => api.get(`/api/v1/courses/${id}/analytics`),
  getAtRisk:   (id: string)    => api.get(`/api/v1/courses/${id}/analytics/at-risk`),
  getGradeWeights:(id: string) => api.get(`/api/v1/courses/${id}/grade-weights`),
  setGradeWeights:(id: string, data: Record<string, number>) => api.post(`/api/v1/courses/${id}/grade-weights`, data),
  getAttendance:(id: string)   => api.get(`/api/v1/courses/${id}/attendance`),
  createAttendanceSession:(id: string, data: Record<string, unknown>)=> api.post(`/api/v1/courses/${id}/attendance`, data),
  markAttendance: (sessionId: string, records: { studentId: string, status: string }[]) => api.post(`/api/v1/attendance/${sessionId}/mark`, { records }),
  getSessionRecords: (sessionId: string) => api.get(`/api/v1/attendance/${sessionId}`),
  getStudentAttendance: (courseId: string) => api.get(`/api/v1/students/me/attendance/${courseId}`),
  getAnnouncements:(id: string)=> api.get(`/api/v1/courses/${id}/announcements`),
  createAnnouncement:(id: string, data: { title: string; body: string })=>api.post(`/api/v1/courses/${id}/announcements`,data),
  getDiscussions:(id: string)  => api.get(`/api/v1/courses/${id}/discussions`),
  createDiscussion:(id: string, data: { title: string; body: string })=> api.post(`/api/v1/courses/${id}/discussions`, data),
  getLiveSessions:(id: string) => api.get(`/api/v1/courses/${id}/live-sessions`),
  createLiveSession:(id: string, data: Record<string, unknown>)=>api.post(`/api/v1/courses/${id}/live-sessions`,data),
  getModuleContent: (modId: string) => api.get(`/api/v1/modules/${modId}/content`),
  uploadContent: (modId: string, data: FormData) => api.post(`/api/v1/modules/${modId}/content`, data, {
    headers: { 'Content-Type': 'multipart/form-data' },
  }),
  deleteContent: (contentId: string) => api.delete(`/api/v1/content/${contentId}`),
  getAssignment: (id: string) => api.get(`/api/v1/assignments/${id}`),
  getMySubmission: (id: string) => api.get(`/api/v1/assignments/${id}/my-submission`),
  getSubmissions: (id: string) => api.get(`/api/v1/assignments/${id}/submissions`),
  submitAssignment: (id: string, data: FormData) => api.post(`/api/v1/assignments/${id}/submit`, data, {
    headers: { 'Content-Type': 'multipart/form-data' }
  }),
  gradeSubmission: (subId: string, data: { grade: number, feedback: string }) => api.patch(`/api/v1/submissions/${subId}/grade`, data),
  getGlobalMilestones: () => api.get('/api/v1/students/me/milestones'),
  startLiveSession: (id: string) => api.patch(`/api/v1/live-sessions/${id}/start`),
  endLiveSession: (id: string) => api.patch(`/api/v1/live-sessions/${id}/end`),
  joinLiveSession: (id: string) => api.get(`/api/v1/live-sessions/${id}/join`),
  getMySubmissions: (courseId: string) => api.get(`/api/v1/courses/${courseId}/my-submissions`),
  getStudentGrades: (courseId: string) => api.get(`/api/v1/students/me/grades/${courseId}`),
  getStudentFinalGrade: (courseId: string) => api.get(`/api/v1/students/me/grades/${courseId}/final`),
};
